version: '3.9'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wkBsT1WyPxAEAzS9
      POSTGRES_DB: autofix
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mingeso-monolothic
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/autofix
      POSTGRES_USER: postgres
      POSTGRES_PASS: wkBsT1WyPxAEAzS9
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgres
    networks:
      - mingeso-monolothic
networks:
  mingeso-monolothic: