version: '3.9'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      TZ: America/Santiago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wkBsT1WyPxAEAzS9
      POSTGRES_DB: autofix
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mingeso-monolothic
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      TZ: America/Santiago
      SEEDER_ENABLED: "false"
      POSTGRES_URL: jdbc:postgresql://postgres:5432/autofix
      POSTGRES_USER: postgres
      POSTGRES_PASS: wkBsT1WyPxAEAzS9
      SERVER_PORT: 8080
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgres
    networks:
      - mingeso-monolothic
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      TZ: America/Santiago
      BACKEND_URI: http://backend:8080/
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    depends_on:
      - postgres
    networks:
      - mingeso-monolothic
networks:
  mingeso-monolothic: