FROM eclipse-temurin:17-jdk-focal
WORKDIR /app
 
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
 
COPY src ./src
CMD [ "./mvnw", "test", "-Dspring.profiles.active=test" ]
# CMD [ "./mvnw", "test", "-Dspring.profiles.active=test", "-Dtest=ReparacionControllerTest#testDeleteReparacion" 
# mvn test -Dtest=MySpecificTest
# mvn test -Dtest=TestClass1,TestClass2]