version: "3.8"
services:
  # Database
  postgres:
    container_name: autofix-postgres
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - autofix-postgres-volume:/var/lib/postgresql/data
    networks:
      - autofix-backend-network
    environment:
      TZ: America/Santiago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wkBsT1WyPxAEAzS9
      POSTGRES_DB: autofix
    ports:
      - 5435:5432
  # Backend & Frontend
  backend:
    container_name: autofix-backend
    image: polloh/gestion-estudiantes-backend
    ports:
      - 8091:8090
    environment:
      DB_HOST: autofix-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - autofix-backend-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  react1:
    container_name: gestion-estudiantes-frontend-container-1
    image: polloh/gestion-estudiantes-frontend
    ports:
      - 3001:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: gestion-estudiantes-frontend-container-2
    image: polloh/gestion-estudiantes-frontend
    ports:
      - 3002:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: gestion-estudiantes-frontend-container-3
    image: polloh/gestion-estudiantes-frontend
    networks:
      - autofix-frontend-network
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: gestion-estudiantes-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3
  nginx-frontend:
    image: nginx
    container_name: gestion-estudiantes-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-frontend-network
    depends_on:
      - react1
      - react2
      - react3
volumes:
  autofix-postgres-volume:
networks:
  autofix-frontend-network:
  autofix-backend-network: