version: "3.8"
services:
  # Database
  postgres:
    container_name: autofix-postgres
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - autofix-postgres-volume:/var/lib/postgresql/data
    networks:
      - autofix-network
    environment:
      TZ: America/Santiago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wkBsT1WyPxAEAzS9
      POSTGRES_DB: autofix
  # Backend & Frontend
  backend:
    image: estebanglochon/autofix-monolothic-backend
    environment:
      SERVER_PORT: 8090
      DB_HOST: autofix-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - autofix-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  frontend:
    image: estebanglochon/autofix-monolothic-frontend
    networks:
      - autofix-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
  # Nginx servers
  nginx:
    container_name: autofix-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-network
    depends_on:
      - frontend
      - backend
volumes:
  autofix-postgres-volume:
networks:
  autofix-network:
